### ISSUE TITLE
No menu items when addin d3js visual to blank pbix

### ISSUE THREAD

**Issue by klassej** [liprec/powerbi-d3jsvisual#9]
When I want to add the visual to a new pbix I can't see the d3js menu items/toolbar.

1. Add the visual to a pbix (or create a new page in the sample file)
2. Click "edit" up on the right hand side
3. No menu items are showing
![d3js](https://user-images.githubusercontent.com/22279754/44042904-cf07f2ae-9f21-11e8-9ed2-983c3f8144b2.PNG)

Tried it in Power BI March 2018 (on premises) and PBI Desktop Version: 2.61.5192.601 64-bit (August 2018)

**Comment by liprec** [comment]
This is 'normal' behavior of custom visuals in Power BI: they need data before they are initiated.
So if you add at least one field to the fields pane of the visual, the editor will appear.

-JP

**Comment by klassej** [comment]
Thanks, closing
